import Header from "../components/layout/Header";
import AppContext from "../components/AppContext";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-dark`}>
        <AppContext >
          <main className="max-w-6xl mx-auto p-4 ">
            <Header />
            {children}
          </main>
        </AppContext>
      </body>
    </html>
  );
}